"""empty message

Revision ID: a91e611c14bd
Revises: 6b61f70fb6cc
Create Date: 2021-03-20 15:21:46.078567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91e611c14bd'
down_revision = '6b61f70fb6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('downvote_count', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('upvote_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('downvote_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('upvote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'upvote_count')
    op.drop_column('post', 'downvote_count')
    op.drop_column('comment', 'upvote_count')
    op.drop_column('comment', 'downvote_count')
    # ### end Alembic commands ###
